spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/security

mybatis:
  mapperLocations:  classpath*:mapper/*Mapper.xml
  typeAliasesPackage: >
    study.wyy.security.pojo