spring:
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/security

mybatis:
  mapperLocations:  classpath*:mapper/*Mapper.xml
  typeAliasesPackage: >
    study.wyy.security.pojo

wyy:
  security:
    image-code:
      length: 5
